export const ACCENTS = {
  blue: {
    label: "Blue",
    swatch: "bg-white",
    face: "bg-white border-zinc-200",
    title: "text-zinc-900",
    muted: "text-zinc-500",
    badge: "bg-zinc-100 text-zinc-600 border border-zinc-200",
    glow: "shadow-apple-sm",
    chip: "bg-zinc-50 text-zinc-700 border-zinc-200",
    ring: "hover:border-[#007AFF]",
  },
  violet: {
    label: "Violet",
    swatch: "bg-white",
    face: "bg-white border-zinc-200",
    title: "text-zinc-900",
    muted: "text-zinc-500",
    badge: "bg-zinc-100 text-zinc-600 border border-zinc-200",
    glow: "shadow-apple-sm",
    chip: "bg-zinc-50 text-zinc-700 border-zinc-200",
    ring: "hover:border-[#007AFF]",
  },
  emerald: {
    label: "Emerald",
    swatch: "bg-white",
    face: "bg-white border-zinc-200",
    title: "text-zinc-900",
    muted: "text-zinc-500",
    badge: "bg-zinc-100 text-zinc-600 border border-zinc-200",
    glow: "shadow-apple-sm",
    chip: "bg-zinc-50 text-zinc-700 border-zinc-200",
    ring: "hover:border-[#007AFF]",
  },
  amber: {
    label: "Amber",
    swatch: "bg-white",
    face: "bg-white border-zinc-200",
    title: "text-zinc-900",
    muted: "text-zinc-500",
    badge: "bg-zinc-100 text-zinc-600 border border-zinc-200",
    glow: "shadow-apple-sm",
    chip: "bg-zinc-50 text-zinc-700 border-zinc-200",
    ring: "hover:border-[#007AFF]",
  },
  rose: {
    label: "Rose",
    swatch: "bg-white",
    face: "bg-white border-zinc-200",
    title: "text-zinc-900",
    muted: "text-zinc-500",
    badge: "bg-zinc-100 text-zinc-600 border border-zinc-200",
    glow: "shadow-apple-sm",
    chip: "bg-zinc-50 text-zinc-700 border-zinc-200",
    ring: "hover:border-[#007AFF]",
  },
  cyan: {
    label: "Cyan",
    swatch: "bg-white",
    face: "bg-white border-zinc-200",
    title: "text-zinc-900",
    muted: "text-zinc-500",
    badge: "bg-zinc-100 text-zinc-600 border border-zinc-200",
    glow: "shadow-apple-sm",
    chip: "bg-zinc-50 text-zinc-700 border-zinc-200",
    ring: "hover:border-[#007AFF]",
  },
  indigo: {
    label: "Indigo",
    swatch: "bg-white",
    face: "bg-white border-zinc-200",
    title: "text-zinc-900",
    muted: "text-zinc-500",
    badge: "bg-zinc-100 text-zinc-600 border border-zinc-200",
    glow: "shadow-apple-sm",
    chip: "bg-zinc-50 text-zinc-700 border-zinc-200",
    ring: "hover:border-[#007AFF]",
  },
  teal: {
    label: "Teal",
    swatch: "bg-white",
    face: "bg-white border-zinc-200",
    title: "text-zinc-900",
    muted: "text-zinc-500",
    badge: "bg-zinc-100 text-zinc-600 border border-zinc-200",
    glow: "shadow-apple-sm",
    chip: "bg-zinc-50 text-zinc-700 border-zinc-200",
    ring: "hover:border-[#007AFF]",
  },
};

export const ACCENT_KEYS = Object.keys(ACCENTS);
export const getAccent = (name) => ACCENTS[name] || ACCENTS.blue;
